package assignment4clientt;

import java.util.StringTokenizer;
import org.jeromq.ZMQ;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matt
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        PartsListButton = new javax.swing.JButton();
        AddParts = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayScreen = new javax.swing.JTextPane();
        PartsName = new javax.swing.JTextField();
        PartsQuantity = new javax.swing.JTextField();
        CheckOrder = new javax.swing.JButton();
        PartsNameLabel = new javax.swing.JLabel();
        PartsQuantityLabel = new javax.swing.JLabel();
        OrderButton = new javax.swing.JButton();
        OrderTextField = new javax.swing.JTextField();
        OrderLabel = new javax.swing.JLabel();
        Message = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PartsListButton.setText("Parts List and Quantity");
        PartsListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartsListButtonActionPerformed(evt);
            }
        });

        AddParts.setText("Add Parts");
        AddParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPartsActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(DisplayScreen);

        PartsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartsNameActionPerformed(evt);
            }
        });

        PartsQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartsQuantityActionPerformed(evt);
            }
        });

        CheckOrder.setText("Check All Orders");
        CheckOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOrderActionPerformed(evt);
            }
        });

        PartsNameLabel.setText("Parts Name");

        PartsQuantityLabel.setText("Parts Quantity");

        OrderButton.setText("Check Order Number");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        OrderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderTextFieldActionPerformed(evt);
            }
        });

        OrderLabel.setText("Order Number");

        Message.setText("Message Order");
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("PARTS ORDER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(AddParts))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(OrderButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Message)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PartsNameLabel)
                            .addComponent(PartsName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(PartsQuantity))
                            .addComponent(PartsQuantityLabel))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderLabel)
                            .addComponent(OrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PartsListButton)
                    .addComponent(CheckOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PartsListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOrder)
                        .addGap(5, 5, 5)
                        .addComponent(Message))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PartsNameLabel)
                            .addComponent(PartsQuantityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PartsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PartsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddParts))))
                .addGap(14, 14, 14)
                .addComponent(OrderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderButton)
                    .addComponent(OrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartsListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartsListButtonActionPerformed

        DisplayScreen.setText(partsList());
        // Add Item
        
    }//GEN-LAST:event_PartsListButtonActionPerformed

    private void AddPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPartsActionPerformed


        //add Parts Button
        DisplayScreen.setText(null);
        String parts = PartsName.getText();
        int quantity = Integer.parseInt(PartsQuantity.getText());
        if(checkDatabase(parts)){
        add(parts,quantity); 
        DisplayScreen.setText("Parts selected: " + parts + "\n" + "Quanitity: " + quantity );
        // int total = quantity * ;
        }
        
        
        
    }//GEN-LAST:event_AddPartsActionPerformed

    private void CheckOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOrderActionPerformed
        //Check Order Button
        DisplayScreen.setText(null);
        int orderNumber = Integer.parseInt(OrderTextField.getText());
        String checkOrders = checkOrder();
 //        StringTokenizer st = new StringTokenizer(checkOrders);
  //   while (st.hasMoreTokens()) {
   //      System.out.println(st.nextToken());
    // }
        DisplayScreen.setText(checkOrders);
        
        
    }//GEN-LAST:event_CheckOrderActionPerformed

    private void PartsQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartsQuantityActionPerformed
        //TextField for Quantitiy
    }//GEN-LAST:event_PartsQuantityActionPerformed

    private void PartsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartsNameActionPerformed
        // TextField for PartName
        

        
    }//GEN-LAST:event_PartsNameActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed

int orderNumber = Integer.parseInt(OrderTextField.getText());
String display = check(orderNumber);

DisplayScreen.setText("Order Number: " + orderNumber + "\n" + "Order " + display );


        // TODO add your handling code here:
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void OrderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderTextFieldActionPerformed
        
         
        
    }//GEN-LAST:event_OrderTextFieldActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed

      ZMQ.Context context = ZMQ.context(1); // thread pool size 1
      ZMQ.Socket socket = context.socket(ZMQ.REQ);
      socket.connect("tcp://localhost:8890");
      // send message to socket
      String checkOrders = checkOrder();
      byte[] request = checkOrders.getBytes();
      socket.send(request, 0); // blocking by default
      // block for response
      byte[] response = socket.recv(0);
      String greeting = new String(response);
      System.out.println("ZeroMQGreetingClient received greeting "
         + greeting);
      socket.close();
      context.term();
      System.out.println("ZeroMQGreetingClient stopping");



        // TODO add your handling code here:
    }//GEN-LAST:event_MessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddParts;
    private javax.swing.JButton CheckOrder;
    private javax.swing.JTextPane DisplayScreen;
    private javax.swing.JButton Message;
    private javax.swing.JButton OrderButton;
    private javax.swing.JLabel OrderLabel;
    private javax.swing.JTextField OrderTextField;
    private javax.swing.JButton PartsListButton;
    private javax.swing.JTextField PartsName;
    private javax.swing.JLabel PartsNameLabel;
    private javax.swing.JTextField PartsQuantity;
    private javax.swing.JLabel PartsQuantityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private static String partsList() {
        com.webservices.OrderWebservice_Service service = new com.webservices.OrderWebservice_Service();
        com.webservices.OrderWebservice port = service.getOrderWebservicePort();
        return port.partsList();
    }

    private static int add(java.lang.String arg0, int arg1) {
        com.webservices.OrderWebservice_Service service = new com.webservices.OrderWebservice_Service();
        com.webservices.OrderWebservice port = service.getOrderWebservicePort();
        return port.add(arg0, arg1);
    }

    private static String checkOrder() {
        com.webservices.OrderWebservice_Service service = new com.webservices.OrderWebservice_Service();
        com.webservices.OrderWebservice port = service.getOrderWebservicePort();
        return port.checkOrder();
    }

    private static String check(int arg0) {
        com.webservices.OrderWebservice_Service service = new com.webservices.OrderWebservice_Service();
        com.webservices.OrderWebservice port = service.getOrderWebservicePort();
        return port.check(arg0);
    }



    private static boolean checkDatabase(java.lang.String arg0) {
        com.webservices.OrderWebservice_Service service = new com.webservices.OrderWebservice_Service();
        com.webservices.OrderWebservice port = service.getOrderWebservicePort();
        return port.checkDatabase(arg0);
    }

    
}
